### ISSUE TITLE
"GetImageSize_" node

### ISSUE THREAD

**Issue by sperrault** [seghier/Grasshopper_ComfyUI#1]
In image2image.json example,
on line 317
"GetImageSize_" should be replaced with "GetImageSize"

**Comment by seghier** [comment]
Install ComfyUI Manager

https://github.com/ltdrdata/ComfyUI-Manager

Then click Install missing nodes 

![image](https://github.com/seghier/Grasshopper_ComfyUI/assets/6026588/b2e042a1-fed0-4bae-9628-f7afacfac8d1)

**Comment by sperrault** [comment]
I tried with the Manager, but "GetImageSize_" is not recognized. 
Worked by removing the "_" 
Thanks

**Comment by seghier** [comment]
GetImageSize node is not mine , i can' help with this error
